### ISSUE TITLE
Cannot deploy mysql db because the version is too low

### ISSUE THREAD

**Issue by yogaics** [ttirtawi/indonesiabelajar-eks#1]
Hi, I've tried to deploy this, but as I want to deploy the mysql stack, it stopped and give error, becuase Singapore region doesn't support MySQL 5.7.30 again. Latest version is 5.7.42. How I can resolve this?

**Comment by ttirtawi** [comment]
You can modify `mysqldatabase/lib/mysqldatabase-stack.ts` and update the version there:

```
    const dbhost = new rds.DatabaseInstance(this, 'rds', {
      engine: rds.DatabaseInstanceEngine.mysql(
        {
          version: rds.MysqlEngineVersion.VER_5_7_30,
        }),
```
